name: Keep Alive

on:
  workflow_dispatch:

  schedule:
    - cron: 0 0 */30 * *

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTION_SECRET }}
      - name: Keep Alive
        run: date > .github/KEEP
      - name: Push
        uses: jdSync/git-auto-commit-action@v4
        with:
          commit_message: Keep Alive
          skip_dirty_check: {{ secrets.skip_dirty_check }}
          commit_user_name: {{ secrets.commit_user_name }}
          commit_user_email: ${{ secrets.commit_user_email }}
          commit_author: ${{ secrets.commit_author }}
