name: gitee

on:
  push:
  watch:
    types: started
  schedule:
    - cron: '0 23 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@v1.0
        with:
          src: ${{ secrets.src }}
          dst: ${{ secrets.dst }}
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.dst_token }}
          account_type: org
          timeout: '1h'
          debug: true
          force_update: true
