name: repo

on:
  workflow_dispatch:

  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/Repo-Sync.yaml'

  schedule:
    - cron: 3-53/10 * * * *

jobs:
  microsoft-365-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep Random Time
        run: sleep $(shuf -i 10-60 -n 1)
      - uses: actions/checkout@v2
      - name: Github ➡ Github
        id: microsoft-365-admin-update
        run: |
          dir=$(pwd)
          bash Scripts/Sync.sh \
            https://github.com/6mb/Microsoft-365-Admin master \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/Microsoft-365-Admin keep
          [ -f /tmp/update ] && mv /tmp/dest_repo $dir || echo "::set-output name=status::updated"
      - name: Set up Docker Buildx
        if: steps.microsoft-365-admin-update.outputs.status != 'updated'
        uses: docker/setup-buildx-action@v1
      - name: Github Docker Login
        if: steps.microsoft-365-admin-update.outputs.status != 'updated'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: jdSync
          password: ${{ secrets.ACTION_SECRET }}
      - name: Build and push
        if: steps.microsoft-365-admin-update.outputs.status != 'updated'
        uses: docker/build-push-action@v2
        with:
          context: ./dest_repo
          file: ./dest_repo/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jdSync/microsoft-365-admin:latest

  gh-card:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep Random Time
        run: sleep $(shuf -i 10-60 -n 1)
      - uses: actions/checkout@v2
      - name: Github ➡ Github
        id: gh-card-update
        run: |
          dir=$(pwd)
          bash Scripts/Sync.sh \
            https://github.com/nwtgck/gh-card develop \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/gh-card keep
          [ -f /tmp/update ] && mv /tmp/dest_repo $dir || echo "::set-output name=status::updated"
      - name: Set up Docker Buildx
        if: steps.gh-card-update.outputs.status != 'updated'
        uses: docker/setup-buildx-action@v1
      - name: Github Docker Login
        if: steps.gh-card-update.outputs.status != 'updated'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: jdSync
          password: ${{ secrets.ACTION_SECRET }}
      - name: Build and push for frontend
        if: steps.gh-card-update.outputs.status != 'updated'
        uses: docker/build-push-action@v2
        with:
          context: ./dest_repo/frontend
          file: ./dest_repo/frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jdSync/gh-card:frontend
      - name: Build and push for backend
        if: steps.gh-card-update.outputs.status != 'updated'
        uses: docker/build-push-action@v2
        with:
          context: ./dest_repo/backend
          file: ./dest_repo/backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jdSync/gh-card:backend

  china-unicom:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep Random Time
        run: sleep $(shuf -i 10-60 -n 1)
      - uses: actions/checkout@v2
      - name: Github ➡ Github
        id: china-unicom-update
        run: |
          dir=$(pwd)
          bash Scripts/Sync.sh \
            https://github.com/simo8102/chinaunicom-AutoSignMachine main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/China-Unicom keep
          [ -f /tmp/update ] && mv /tmp/dest_repo $dir || echo "::set-output name=status::updated"
      - name: Modify Dockerfile
        if: steps.china-unicom-update.outputs.status != 'updated'
        run: |
          sed -i 's/mirrors.tuna.tsinghua.edu.cn/dl-cdn.alpinelinux.org/g' ./dest_repo/docker/Dockerfile
          sed -i 's/registry.npm.taobao.org/registry.npmjs.org/g' ./dest_repo/docker/Dockerfile
          cat ./dest_repo/docker/Dockerfile
      - name: Set up Docker Buildx
        if: steps.china-unicom-update.outputs.status != 'updated'
        uses: docker/setup-buildx-action@v1
      - name: Github Docker Login
        if: steps.china-unicom-update.outputs.status != 'updated'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: jdSync
          password: ${{ secrets.ACTION_SECRET }}
      - name: Build and push
        if: steps.china-unicom-update.outputs.status != 'updated'
        uses: docker/build-push-action@v2
        with:
          context: ./dest_repo
          file: ./dest_repo/docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jdSync/china-unicom:latest

  jd-panel:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep Random Time
        run: sleep $(shuf -i 10-60 -n 1)
      - uses: actions/checkout@v2
      - name: Github ➡ Github
        id: jd-panel-update
        run: |
          dir=$(pwd)
          bash Scripts/Sync.sh \
            https://github.com/whyour/qinglong master \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/JD-Panel keep
          [ -f /tmp/update ] && mv /tmp/dest_repo $dir || echo "::set-output name=status::updated"
      - name: Set up Docker Buildx
        if: steps.jd-panel-update.outputs.status != 'updated'
        uses: docker/setup-buildx-action@v1
      - name: Github Docker Login
        if: steps.jd-panel-update.outputs.status != 'updated'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: jdSync
          password: ${{ secrets.ACTION_SECRET }}
      - name: Build and push
        if: steps.jd-panel-update.outputs.status != 'updated'
        uses: docker/build-push-action@v2
        with:
          context: ./dest_repo
          file: ./dest_repo/docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jdSync/jd-panel:latest

  jd-cookie:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep Random Time
        run: sleep $(shuf -i 10-60 -n 1)
      - uses: actions/checkout@v2
      - name: Github ➡ Github
        id: jd-cookie-update
        run: |
          dir=$(pwd)
          bash Scripts/Sync.sh \
            https://github.com/scjtqs2/jd_cookie master \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/JD-Cookie keep
          [ -f /tmp/update ] && mv /tmp/dest_repo $dir || echo "::set-output name=status::updated"
      - name: Set up Docker Buildx
        if: steps.jd-cookie-update.outputs.status != 'updated'
        uses: docker/setup-buildx-action@v1
      - name: Github Docker Login
        if: steps.jd-cookie-update.outputs.status != 'updated'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: jdSync
          password: ${{ secrets.ACTION_SECRET }}
      - name: Build and push
        if: steps.jd-cookie-update.outputs.status != 'updated'
        uses: docker/build-push-action@v2
        with:
          context: ./dest_repo
          file: ./dest_repo/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jdSync/jd-cookie:latest

  jd-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep Random Time
        run: sleep $(shuf -i 10-60 -n 1)
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Bot
        run: |
          bash Scripts/Sync.sh \
            https://github.com/SuMaiKaDe/bot main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/JD-Bot
      - name: JDHelloWorld
        run: |
          bash Scripts/Sync.sh \
            https://github.com/JDHelloWorld/jd_scripts main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/jd-scripts ts2js
      - name: hundun
        run: |
          bash Scripts/Sync.sh \
            https://github.com/whyour/hundun master \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/hundun
      - name: ZCY01
        run: |
          bash Scripts/Sync.sh \
            https://github.com/ZCY01/daily_scripts main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/ZCY01
      - name: yangtingxiao
        run: |
          bash Scripts/Sync.sh \
            https://github.com/yangtingxiao/QuantumultX master \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/yangtingxiao
      - name: JDDJ
        run: |
          bash Scripts/Sync.sh \
            https://github.com/passerby-b/JDDJ main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/JDDJ
      - name: longzhuzhu
        run: |
          bash Scripts/Sync.sh \
            https://github.com/longzhuzhu/nianyu main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/longzhuzhu
      - name: Ariszy
        run: |
          bash Scripts/Sync.sh \
            https://github.com/Ariszy/Private-Script master \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/Ariszy
      - name: moposmall
        run: |
          bash Scripts/Sync.sh \
            https://github.com/moposmall/Script main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/moposmall
      - name: pxylen
        run: |
          bash Scripts/Sync.sh \
            https://github.com/pxylen/dog_jd master \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/pxylen
      - name: ztxtop
        run: |
          bash Scripts/Sync.sh \
            https://github.com/ztxtop/x main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/ztxtop
      - name: airacg
        run: |
          bash Scripts/Sync.sh \
            https://github.com/airacg/jd_task main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/airacg
      - name: JD_Diy
        run: |
          bash Scripts/Sync.sh \
            https://github.com/chiupam/JD_Diy master \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/JD-Diy
      - name: Sunert
        run: |
          bash Scripts/Sync.sh \
            https://github.com/Sunert/Script master \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/Sunert
      - name: curtinlv
        run: |
          bash Scripts/Sync.sh \
            https://github.com/curtinlv/JD-Script main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/curtinlv
      - name: Tsukasa007
        run: |
          bash Scripts/Sync.sh \
            https://github.com/Tsukasa007/my_script master \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/Tsukasa007
      - name: jiulan
        run: |
          bash Scripts/Sync.sh \
            https://github.com/jiulan/platypus main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/jiulan
      - name: star261
        run: |
          bash Scripts/Sync.sh \
            https://github.com/star261/jd main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/star261
      - name: smiek2221
        run: |
          bash Scripts/Sync.sh \
            https://github.com/smiek2221/scripts master \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/smiek2221
      - name: X1a0He
        run: |
          bash Scripts/Sync.sh \
            https://github.com/X1a0He/jd_scripts_fixed main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/X1a0He

  vpay:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep Random Time
        run: sleep $(shuf -i 10-60 -n 1)
      - uses: actions/checkout@v2
      - name: Github ➡ Github
        run: |
          bash Scripts/Sync.sh \
            https://gitee.com/pmhw/Vpay master \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/jdSync/VPay
